### ISSUE TITLE
Alternative script idea

### ISSUE THREAD

**Issue by knaccc** [alvinjoelsantos/promo-video#3]
Let’s recap. Amounts of Monero exist on the blockchain in the form of ‘outputs’. When you own Monero, it means that you control some of these outputs. Each output can have a different value, such as 1 XMR or 5 XMR. You have a secret key for each output that you own, that allows you alone to spend it.

When you send someone Monero, what you are doing is announcing to the Monero network that the value of some of your outputs should now be under someone else’s control. This announcement is called a transaction. Since only the recipient should have control over the outputs that you send them, your transaction takes your outputs and creates a new set of outputs for the recipient that only the recipient will have the ability to control.

To safeguard the recipient’s privacy, you do not announce to the Monero network that these new outputs belong to the recipient’s wallet address. Instead, you encrypt the new outputs such that only the recipient knows how to scan the blockchain to discover them. It is because a wallet address never appears on the blockchain that wallet addresses are considered to be “stealth addresses”.

To understand how this encryption works, you first need to understand what a key pair is.

A key pair consists of a public key and a private key. If someone tells you their public key, you can use that public key to encrypt information such that only they can decrypt it with their private key.

The recipient's wallet address consists of two public keys, called the public view key and the public spend key. When you encrypt a payment for them, you use their public view key to encrypt the output so that only they can see that it exists on the blockchain by using their private view key. You also use their public spend key to encrypt the output so that only they can control and therefore spend the funds by using their private spend key.

Notice that this means that the recipient can give out their private view key so that an auditor can have visibility over the funds they receive. Because they are giving out their public view key but not their public spend key, they do not need to worry that the auditor can spend their funds.

In our next video, we discuss a concept called a ‘ring signature’. We’ll see how this greatly increases the level of privacy in a transaction so that observers cannot know the value of the Monero being sent and cannot know which outputs were actually the source of the transaction.

**Comment by scoobybejesus** [comment]
Let’s recap. Monero exist on the blockchain in the form of ‘outputs’. When you own monero, it means that you have exclusive control over some of these outputs.  When you send someone monero, you are announcing to the Monero network that you wish to consume some of your outputs, and create brand new outputs for someone else. In order for you to send monero, the recipient must first provide you with their public address. Using their public address, your wallet will create new outputs in such a way that only the intended recipient is able to recognize and spend them. Let's more deeply explore this concept.

The transaction your wallet broadcasts to the Monero network does not reflect the recipient's public address. Rather, your wallet encrypts the new outputs such that only the recipient will recognize them as his. As a result, Monero's blockchain consists of outputs that are not linkable to, or associated with, any public address. This clever feature is why Monero public addresses are also called “stealth addresses.” Stealth addresses are what protect the privacy and identity of Monero recipients.

Based on that explanation, you may be wondering what it means to encrypt an output. Well, buckle your seat belts, because we're about to get technical.

A Monero public address is made up of two parts: a public spend key and a public view key. When you send someone Monero, your wallet will use each of those keys to form their new output. Using the recipient's public view key, your wallet will compute a random shared secret, only knowable by your wallet and the recipient's wallet. Then your wallet will use the shared secret - along with the recipient's public spend key - to create a unique, one-time public key (their output!). 

You heard that right; Monero outputs are also called one-time public keys. One-time public keys are what reside on the blockchain and can be seen by everyone. Even though everyone can see the one-time public key you sent, no one knows to which public address it was sent, because outside observers can not know the shared secret. Using its private view key, the recipient's wallet can recompute the shared secret; therefore, only the recipient's wallet is able to identify the one-time public key as belonging to him.

As you can see, stealth addresses protect the privacy and identity of recipients. 
On the input side of the transaction, the sender's privacy is shielded with the use of ring signatures. Ring signatures help obfuscate the source of transactions, by including various foreign outputs with the “real” output. We'll discuss ring signatures and Monero's other privacy features in greater detail in another video.

If you are interested in what makes Monero the leading privacy-centric cryptocurrency, please check out the other videos or visit getmonero.org.

**Comment by scoobybejesus** [comment]
I took your approach and melded it with the original.

**Comment by knaccc** [comment]
##1) - Intro
Monero is secure, electronic, untraceable cash. It is open-source, decentralized, and freely accessible to all. In this video, we will focus on stealth addresses.

##2) - Technology recap
Let's take a step back, and recap some concepts from the previous video. We learned that Monero uses blockchain technology to record transactions. When Alice owns Monero, it means that she has exclusive control over some outputs. When Alice sends Monero to Bob, Alice is announcing to the network that she wishes to transfer the value from her outputs to a set of new outputs which only Bob can control. Let's take this a step further, and see how stealth addresses enhance Monero’s privacy.

##3) - Stealth Addresses
Monero has stealth addresses. What this means is that when Alice sends Monero to Bob, the outputs Alice spends would not have been publicly associated with Alice’s wallet address on the blockchain prior to being sent, and the outputs Bob receives will not be publicly associated with Bob’s wallet address when Bob receives them. Bob therefore knows that no one else can see that any Monero is being sent to him. If Alice chooses, Bob cannot even know that it was Alice’s wallet that sent funds to him. If Alice ever needs to prove that she sent Monero to Bob, then her wallet alone will have the ability to do so.

##4) – Implementation details
Each Monero wallet address is a 95 character string, which stores a public view key and a public spend key. 
When Alice sends Monero to Bob, Alice will create a new output for Bob such that only Bob can see that it is destined for him, and such that only Bob can spend it.
Alice does this by generating a one-time public key for Bob’s new output using Bob’s public view key and Bob’s public spend key.
This one-time public key is specially constructed so that only Bob’s private view key can be used to detect that the output is destined for him. Everyone can see that the one-time public key exists on the blockchain, but only Alice and Bob know that it belongs to Bob.
Bob’s wallet constantly scans the blockchain with his private view key to see if any new outputs are destined for him. After Bob detects that an output is destined for him, only Bob can use his private spend key to mathematically calculate the one-time private key that corresponds to the output’s one-time public key. It is this one-time private key that allows Bob to spend the output later.
Note that it does not matter if Bob is offline when the transaction is sent. Bob can scan the blockchain at any future time to see if any funds have been sent to him.

##5) - Untraceability
As you can see, stealth addresses protect outputs from being associated with wallet addresses. Bob however still needs to ensure that Alice cannot tell if or when he decides to spend the outputs that Alice sent him. This is achieved with a ring signature, which allows Bob to hide which outputs he is using when spending Monero in a transaction. 

##6) – Next time
In our next video, we’ll discuss the ring signature concept in more detail and see how this feature creates untraceability in Monero. If you are interested in what makes Monero the leading privacy-centric cryptocurrency, please check out the other videos or visit getmonero.org.

**Comment by scoobybejesus** [comment]
Mostly subtle tweaks.

##1) - Intro
Monero is secure, untraceable, electronic cash. It is open-source, decentralized, and freely accessible to all. In this video, we will focus on stealth addresses.   \\Swapped placement of untraceable and electronic.

##2) - Technology recap
Let's take a step back, and recap some concepts from the previous video. 
We learned that Monero uses a blockchain to record transactions. 
If Alice owns monero, it means that she has exclusive control over some outputs that have been previously recorded on the blockchain. 
When Alice sends monero to Bob, Alice is announcing to the network that she wishes to transfer the value from her outputs to a set of new outputs which only Bob can know are his and control. 
Now let's take this a step further, to see how stealth addresses enhance Monero’s privacy.

##3) - Stealth Addresses
Monero has stealth addresses. 
What this means is that Alice's outputs are not publicly associated with Alice’s wallet address, since the address is not recorded on the blockchain.
When Alice sends monero to Bob, the outputs Bob receives will similarly not be publicly associated with Bob’s wallet address. 
Bob, therefore, knows that no one else can see when or if any monero is sent to him. 
The following are some fairly technical details regarding how stealth addresses are implemented.

//Bob cannot even know that it was Alice’s wallet that sent funds to him, unless she chooses to identify herself.   //  Keep these?  Informative, but not really related to stealth addressess.
//If Alice ever needs to prove that she sent Monero to Bob, then her wallet alone will have the ability to do so.   //  These are more about Alice's side of the tx, instead of Bob's.

##4) – Implementation details
Each Monero wallet address is a 95-character string, which stores a public view key and a public spend key.
When Alice sends monero to Bob, Alice will create a new output for Bob such that only Bob can see that it is destined for him, and such that only Bob can spend it.
Alice does this by using Bob’s public view key and Bob’s public spend key to generate a one-time public key for Bob’s new output.
This one-time public key is specially constructed so that only Bob’s private view key can be used to detect that the output is destined for him. 
Everyone can see that the one-time public key exists on the blockchain, but only Alice and Bob know that it belongs to Bob.
Bob’s wallet constantly scans the blockchain with his private view key to see if any new outputs are destined for him. 
After Bob detects that an output is destined for him, only Bob can use his private spend key to mathematically calculate the one-time private key that corresponds to the output’s one-time public key. 
It is this one-time private key that allows Bob to spend the output later.
Note that it does not matter if Bob is offline when he is sent monero. 
Bob can scan the blockchain at any time to see if funds have been sent to him.

##5) - Untraceability
As you can see, stealth addresses protect outputs from being associated with wallet addresses. 
Bob however still needs to ensure that Alice cannot tell if or when he decides to spend the outputs that Alice sent him. 
This is achieved with a ring signature, which allows Bob to hide which outputs he is using when spending Monero in a transaction.
In our next video, we’ll discuss the ring signature concept in more detail and see how this feature creates untraceability in Monero. 

##6) – Next time
If you are interested in what makes Monero the leading privacy-centric cryptocurrency, please check out the other videos or visit getmonero.org.

https://paste.fedoraproject.org/paste/eiCQiJyTXV~4ob22nCPIDV5M1UNdIGYhyRLivL9gydE=

**Comment by knaccc** [comment]
I'm fine either way with your edits, I just thought I'd explain my reasoning here:

>> //Bob cannot even know that it was Alice’s wallet that sent funds to him, unless she chooses to identify herself. // Keep these? Informative, but not really related to stealth addressess.

this is a direct consequence/benefit of stealth addressees, because the use of stealth addresses means that the outputs Bob receives cannot be associated with any particular sender's wallet address. Another way of stating the benefit is therefore that It means that if Bob decides to accept payment from someone, he does not need to worry that other people can see that he's receiving payment from any particular source. If he is a merchant, no one can tell how many different customers he has, whether any of them are repeat customers, or if he has any customers at all. This might be too much detail, but on the other hand, people may not realise these are the privacy benefits they are getting as a result of stealth addresses.

>> //If Alice ever needs to prove that she sent Monero to Bob, then her wallet alone will have the ability to do so. // These are more about Alice's side of the tx, instead of Bob's."

I put this in because of the recent Reddit questions I've seen posted where people have asked if "monero is too private", and wondered whether it'd be impossible to prove to anyone that they really did pay.

**Comment by knaccc** [comment]
> If Alice owns Monero, it means that she has exclusive control over some outputs, which was previously recorded on the blockchain

I see how it could be correct whether you say "which was" or "which were", because you may have been referring to the recording of the transaction (which was) rather than the recording of the outputs (which were). However, since you did not explicitly state it was the transaction you were referring to, the use of "which was" instead of "which were" will sound strange to a lot of people's ears I think.

>Now let's take this a step further, to see how stealth addresses enhances a user’s privacy.

enhances -> enhance

> In every transaction, a stealth address, also known as a one-time public key, is automatically generated and it is where outputs are sent to and recorded on the blockchain

This isn't quite how it works. The stealth address isn't like a memory address or storage address somewhere in the blockchain where we decide to store some data. When a transaction is recorded in a new block, a stealth address is simply stored as part of the transaction in order to specify the one-time public key that must correspond to the one-time private key which must be used to spend that particular output. This is why I hate the term 'stealth address' so much, because it misleads people to think that it is like a memory address somewhere on the blockchain where you can store an output. That's not at all how it actually works.

>An outside observer cannot tell if any transaction is associated to a specific wallet address

associated to -> associated with

> Everyone can see the one-time public key on the blockchain, but only Alice and Bob know about the transaction.

Maybe be more specific here - everyone knows about the transaction, it's just that no one else knows that the transaction involved funds moving from Alice to Bob.

> calculate a one-time private key

this does not explicitly state that the one-time private key has to correspond to the one-time output public key, rather than just being a random private key that is calculated
